### ISSUE TITLE
ovos-installer fails on rpi for Mark 1

### ISSUE THREAD

**Issue by Montanadude** [OpenVoiceOS/ovos-installer#112] opened 2024-07-23 18:07 UTC
I have tried both a rpi 3b+ and also a RPI4 on the Mark 1 and both have failed.
Can someone please help?

Here is the failure 
```
fatal: [127.0.0.1]: FAILED! => {
    "attempts": 5,
    "changed": false,
    "cmd": "/usr/bin/docker --host unix:///var/run/docker.sock compose --ansi never --progress plain --project-directory /tmp/ovos-docker/compose --project-name ovos --file docker-compose.yml --file docker-compose.raspberrypi.yml ps --format json --all --no-trunc",
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "build": "policy",
            "ca_path": null,
            "cli_context": null,
            "client_cert": null,
            "client_key": null,
            "dependencies": true,
            "docker_cli": null,
            "docker_host": "unix:///var/run/docker.sock",
            "env_files": null,
            "files": [
                "docker-compose.yml",
                "docker-compose.raspberrypi.yml"
            ],
            "profiles": null,
            "project_name": "ovos",
            "project_src": "/tmp/ovos-docker/compose",
            "pull": "always",
            "recreate": "auto",
            "remove_images": "all",
            "remove_orphans": true,
            "remove_volumes": true,
            "scale": null,
            "services": null,
            "state": "present",
            "timeout": null,
            "tls": false,
            "tls_hostname": null,
            "validate_certs": false
        }
    },
    "msg": "validating /tmp/ovos-docker/compose/docker-compose.yml: services.ovos_phal_admin.pull_policy services.ovos_phal_admin.pull_policy must be one of the following: \"always\", \"never\", \"if_not_present\", \"build\", \"missing\"",
    "rc": 15,
    "stderr": "validating /tmp/ovos-docker/compose/docker-compose.yml: services.ovos_phal_admin.pull_policy services.ovos_phal_admin.pull_policy must be one of the following: \"always\", \"never\", \"if_not_present\", \"build\", \"missing\"\n",
    "stderr_lines": [
        "validating /tmp/ovos-docker/compose/docker-compose.yml: services.ovos_phal_admin.pull_policy services.ovos_phal_admin.pull_policy must be one of the following: \"always\", \"never\", \"if_not_present\", \"build\", \"missing\""
    ],
    "stdout": "",
    "stdout_lines": []
}
```

and the DPASTE as well

```
++ curl -sF 'content=<-' https://dpaste.com/api/v2/
+ debug_url=https://dpaste.com/8F65EK98K
+ echo -e '\n➤ Unable to finalize the process, please check /var/log/ovos-installer.log for more details.'

➤ Unable to finalize the process, please check /var/log/ovos-installer.log for more details.
+ echo -e '➤ Please share this URL with us https://dpaste.com/8F65EK98K'
➤ Please share this URL with us https://dpaste.com/8F65EK98K
```

**Comment by goldyfruit** [comment] 2024-07-23 21:37
I just tried to deployed OVOS in containers and it went well, I'm not able to reproduce the issue. :disappointed:

```
└─[$] <> docker ps -a
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS                             PORTS     NAMES
36db01876e75   smartgic/ovos-audio:alpha             "/bin/bash /usr/loca…"   50 seconds ago   Up 49 seconds (health: starting)             ovos_audio
924db45933fd   smartgic/ovos-plugin-ggwave:alpha     "/bin/bash -c ovos-g…"   50 seconds ago   Up 49 seconds                                ovos_plugin_ggwave
cb19b80908bb   smartgic/ovos-listener-dinkum:alpha   "/bin/bash /usr/loca…"   50 seconds ago   Up 49 seconds (health: starting)             ovos_listener
595e9a6aa3fa   smartgic/ovos-core:alpha              "/bin/bash /usr/loca…"   50 seconds ago   Up 48 seconds (health: starting)             ovos_core
1c67e63f689e   smartgic/ovos-phal:alpha              "/bin/bash /usr/loca…"   50 seconds ago   Up 49 seconds (health: starting)             ovos_phal
34df3f74df2d   smartgic/ovos-cli:alpha               "sleep infinity"         50 seconds ago   Up 49 seconds                                ovos_cli
03cbc2f4592d   smartgic/ovos-phal-admin:alpha        "/bin/bash /usr/loca…"   50 seconds ago   Up 49 seconds (health: starting)             ovos_phal_admin
b0665a4feae0   smartgic/ovos-messagebus:alpha        "/bin/bash -c ovos-m…"   51 seconds ago   Up 49 seconds (health: starting)             ovos_messagebus
```

- Which version of Raspberry Pi OS did you install?
- How did you run the installer and with which user?

**Comment by Montanadude** [comment] 2024-07-25 12:39
The user was dad.  I'm trying again with the user ovos since from looking thru the scripts it seems to like that.  I'm also using Bookworm lite.

**Comment by goldyfruit** [comment] 2024-07-28 02:06
@Montanadude did you follow all the steps from this howto https://community.openconversational.ai/t/howto-begin-your-open-voice-os-journey-with-the-ovos-installer/14900 ?

**Comment by goldyfruit** [comment] 2024-08-01 19:31
Closing for now, feel free to re-open.

**Closed by goldyfruit** 2024-08-01 19:31 UTC
Labels: waiting from user
