### ISSUE TITLE
fails on Fedora 41 - missing python3-libdnf5

### ISSUE THREAD

**Issue by andlo** [OpenVoiceOS/ovos-installer#203] opened 2024-11-16 22:08 UTC
From installer log i see teese lines:
```
2024-11-15 20:58:33,028 p=7963 u=root n=ansible | Friday 15 November 2024  20:58:33 +0100 (0:00:00.014)       0:00:02.171 ******* 
2024-11-15 20:58:33,306 p=7963 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": false, "failures": [], "msg": "Could not import the libdnf5 python module using /home/andlo/.venvs/ovos-installer/bin/python3 (3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]). Please install python3-libdnf5 package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])"}
2024-11-15 20:58:33,307 p=7963 u=root n=ansible | PLAY RECAP **********************************************************************************************************************************
2024-11-15 20:58:33,307 p=7963 u=root n=ansible | 127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=60   rescued=0    ignored=0   
2024-11-15 20:58:33,307 p=7963 u=root n=ansible | Friday 15 November 2024  20:58:33 +0100 (0:00:00.278)       0:00:02.449 ******* 
```

The issue is proberly in the fedora packaginside, and a bug is alreddy posted for the issue. 

https://bugzilla.redhat.com/show_bug.cgi?id=2322751

So hopefully it will be fixed upstream :)

**Comment by goldyfruit** [comment] 2024-11-17 21:14
Thanks @andlo, the issue is now fixed.

**Closed** 2024-11-17 21:14 UTC
Labels: bug
